name: Deploy to ECS Fargate

on:
  workflow_dispatch:   # ðŸ”¥ Manual trigger only

env:
  TEST_RUN: true   # <-- Set true to only test workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Tag image
        run: |
          docker tag my-app:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Push to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Test ECS Deploy
        if: env.TEST_RUN == 'true'
        run: |
          echo "âœ… TEST_RUN is enabled. Skipping actual ECS deployment."
          echo "Workflow ran successfully!"

      - name: Deploy to ECS
        if: env.TEST_RUN != 'true'
        run: |
          aws ecs update-service \
            --cluster my-ecs-cluster \
            --service my-ecs-service \
            --force-new-deployment
