name: Deploy to ECS Fargate

on:
  workflow_dispatch:
    inputs:
      TEST_RUN:
        description: 'Run workflow in test mode'
        required: true
        default: 'true'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Test AWS Step (skip if TEST_RUN)
        if: github.event.inputs.TEST_RUN == 'true'
        run: |
          echo "âœ… TEST_RUN is enabled. Skipping AWS steps."
          echo "Workflow ran successfully!"

      - name: Configure AWS credentials
        if: github.event.inputs.TEST_RUN != 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to ECS
        if: github.event.inputs.TEST_RUN != 'true'
        run: |
          echo "ðŸ”¥ Deploying to ECS..."
